USE whether_vietnam;

INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('200', 'thunderstorm with light rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('201', 'thunderstorm with rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('202', 'thunderstorm with heavy rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('210', 'light thunderstorm');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('211', 'thunderstorm');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('212', 'heavy thunderstorm');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('221', 'ragged thunderstorm');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('230', 'thunderstorm with light drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('231', 'thunderstorm with drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('232', 'thunderstorm with heavy drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('300', 'light intensity drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('301', 'drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('302', 'heavy intensity drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('310', 'light intensity drizzle rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('311', 'drizzle rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('312', 'heavy intensity drizzle rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('313', 'shower rain and drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('314', 'heavy shower rain and drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('321', 'shower drizzle');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('500', 'light rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('501', 'moderate rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('502', 'heavy intensity rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('503', 'very heavy rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('504', 'extreme rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('511', 'freezing rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('520', 'light intensity shower rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('521', 'shower rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('522', 'heavy intensity shower rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('531', 'ragged shower rain');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('600', 'light snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('601', 'snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('602', 'heavy snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('611', 'sleet');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('612', 'light shower sleet');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('613', 'shower sleet');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('615', 'light rain and snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('616', 'rain and snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('620', 'light shower snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('621', 'shower snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('622', 'heavy shower snow');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('701', 'mist');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('711', 'smoke');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('721', 'haze');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('731', 'sand/dust whirls');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('741', 'fog');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('751', 'sand');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('761', 'dust');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('762', 'volcanic ash');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('771', 'squalls');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('781', 'tornado');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('800', 'clear sky');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('801', 'few clouds: 11-25%');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('802', 'scattered clouds: 25-50%');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('803', 'broken clouds: 51-84%');
INSERT INTO `weather_vietnam`.`general_weather` (`status_id`, `description`) VALUES ('804', 'overcast clouds: 85-100%');